import sys, os
sys.path.insert(0, r"C:\Users\nmurcin\Lumen\local\tmp\swarm\harness")
import cdp
APP = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
srv = cdp.StaticServer(APP).__enter__()
c = cdp.Chrome(); c.launch()
try:
    c.load(srv.url("/index.html"))
    # Test the EXISTING ported rules end-to-end through the generic engine:
    # 1) acid + metal -> metal disappears (class-free specific rule, chance 0.15)
    c.eval("return window.__FLUX.reset()")
    c.eval("return window.__FLUX.reseed(3)")
    c.eval("return window.__FLUX.paintRect(150,100,170,120,'metal')")
    c.eval("return window.__FLUX.paintRect(150,90,170,99,'acid')")
    c.eval("return window.__FLUX.step(0)")
    m0=c.eval("return (window.__STATE__.totals.massByMaterial['metal']||0)")
    c.eval("return window.__FLUX.step(150)")
    m1=c.eval("return (window.__STATE__.totals.massByMaterial['metal']||0)")
    print("acid+metal: metal", m0, "->", m1, "(corroded:", m1<m0, ")")
    # 2) plant + water -> plant grows (chance 0.02)
    c.eval("return window.__FLUX.reset()")
    c.eval("return window.__FLUX.reseed(3)")
    c.eval("return window.__FLUX.paintRect(150,150,152,160,'plant')")
    c.eval("return window.__FLUX.paintRect(120,150,180,170,'water')")
    c.eval("return window.__FLUX.step(0)")
    p0=c.eval("return (window.__STATE__.totals.massByMaterial['plant']||0)")
    c.eval("return window.__FLUX.step(200)")
    p1=c.eval("return (window.__STATE__.totals.massByMaterial['plant']||0)")
    print("plant+water: plant", p0, "->", p1, "(grew:", p1>p0, ")")
    # 3) determinism of the engine: same seed, two runs, identical hash
    def run():
        c.eval("return window.__FLUX.reset()")
        c.eval("return window.__FLUX.reseed(77)")
        c.eval("return window.__FLUX.paintRect(150,100,170,120,'acid')")
        c.eval("return window.__FLUX.paintRect(150,121,170,140,'stone')")
        c.eval("return window.__FLUX.step(120)")
        return c.eval("return window.__FLUX.stateHash()")
    h1=run(); h2=run()
    print("engine determinism: h1==h2:", h1==h2, "(", h1, h2, ")")
finally:
    c.close(); srv.__exit__()
